language: python
python:
  - "2.7"
  - "3.6"
matrix:
  include:
  - python: "2.7"
    env: TOXENV=flake8
cache: pip
addons:
  apt:
    packages:
install:
  - pip install tox-travis codecov
script:
  - tox
after_success:
- codecov
